### ISSUE TITLE
Unresolved import

### ISSUE THREAD

**Issue by SamuelAshcroft** [rakaly/ck3save#11]
Hi Nick,

I'm new to rust, but I don't know where else to turn to solve this issue I'm having. This isn't an issue with the code, I just don't know what I'm doing and can't dm you. With that said:

When I run rustc main.rs, I get this error:

error[E0432]: unresolved import `ck3save`
 --> main.rs:3:5
  |
3 | use ck3save::{Ck3Extractor, Encoding};
  |     ^^^^^^^ maybe a missing crate `ck3save`?
  
  When I run cargo install --list I get this:
  
  ck3save v0.2.10:
    debug_save.exe
    fmt.exe
    melt.exe
    
    This is probably something to do with my rust environment but I thought I'd ask, sorry for raising this as an issue.
    
    Thanks.

**Comment by nickbabcock** [comment]
Make sure you specify ck3save in your Cargo.toml like this: https://github.com/rakaly/cli/blob/e8a06ad3dd477a01e2bcd2edb954a55fdcb12818/Cargo.toml#L12

**Comment by SamuelAshcroft** [comment]
Ah, I ended up using your command line interface, I just needed to melt the file, it's brilliant.

**Comment by nickbabcock** [comment]
Haha, good to hear.
