### ISSUE TITLE
Zip file restriction is too small

### ISSUE THREAD

**Issue by gooftroop** [rakaly/ck3save#14]
I'm attempting to upload a 34493 KB ck3 file (zip file type) but the extraction is failing due to the file size limit. Can this limit be removed? Or at least made into an option?

**Comment by nickbabcock** [comment]
Wow, that is a big save! Anything particular about the save that caused it to grow so large (ie: mods)?

I'm working on a major update to the eu4save crate that removes this error and instead exposes the size as part of the API. I'm going to port it over to ck3 once I'm done, which should be soon.

**Comment by gooftroop** [comment]
I do have a large number of mods that add a considerable amount of modifiers to each character (and a rather large family), so that's likely the culprit. Awesome! Thank you for replying so quickly - I'll keep my eyes out for the update you push

**Comment by gooftroop** [comment]
confirmed that the issue has been resolved - thanks!
