### ISSUE TITLE
Question on AliveData

### ISSUE THREAD

**Issue by gooftroop** [rakaly/ck3save#17]
Not being familiar with Jomni, is it possible to expand the `AliveData` model to include the remaining fields one would expect (i.e. traits)? Is this just done by adding to the model definition? If so I think I can attempt a PR to do so

**Comment by nickbabcock** [comment]
> Is this just done by adding to the model definition?

Yeah! If you wanted to add a trait like fertility, all what you would need to do is:

```diff
index 1e33d0f..5dda8b7 100644
--- a/src/models/gamestate.rs
+++ b/src/models/gamestate.rs
@@ -20,6 +20,7 @@ pub struct AliveData {
     pub gold: Option<f64>,
     pub health: Option<f32>,
     pub income: Option<f32>,
+    pub fertility: Option<f32>,
 }
 
 pub(crate) fn deserialize_eu4_float<'de, D>(deserializer: D) -> Result<Option<f64>, D::Error>
```

Feel free to contribute to expanding the CK3 save data model. I'm not as well versed in CK3 mechanics as I am EU4, so it's a bit barren right now 😄
